//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarEchoEmporium.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public int customerId { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string contactNum { get; set; }
        public System.DateTime birthday { get; set; }
        public System.DateTime registrationDate { get; set; }
    }
}
