//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarEchoEmporium.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int orderId { get; set; }
        public int customerId { get; set; }
        public System.DateTime orderDate { get; set; }
        public int totalPrice { get; set; }
    }
}
