//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EarEchoEmporium.AppData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int productId { get; set; }
        public string productBrand { get; set; }
        public string productModel { get; set; }
        public int productPrice { get; set; }
        public string productTune { get; set; }
        public int productQty { get; set; }
    }
}
